### ISSUE TITLE
Feature request: add "Quit Obsidian" option in Tray's Context Menu

### ISSUE THREAD

**Issue by youngboy** [dragonwocky/obsidian-tray#28]
When the "Run in Background" setting is enabled, it becomes difficult to quit Obsidian through various standard methods. Often, the only option left is to forcefully quit the application. It would be extremely useful to have a "Quit Obsidian" option directly in the system tray's context menu to easily and gracefully exit the application.

**Comment by youngboy** [comment]
Yes, I've tried using the "Close Vault" option. However, to fully quit Obsidian, it seems I have to perform an additional step after clicking "Close Vault." I apologize for not being aware of the multi-vault features; I'm new to Obsidian and thanks for the awesome plugin :)

**Comment by dragonwocky** [comment]
@youngboy hmm, I'm guessing this is a macOS-specific window management behaviour. Would I be right in guessing that in macOS, apps can still be open/running even without any open windows? If so, I probably just need to call either `app.quit()` or `app.exit()` manually if there are no remaining windows open.

**Comment by youngboy** [comment]
> Would I be right in guessing that in macOS, apps can still be open/running even without any open windows

yes, it is still running.

**Comment by dragonwocky** [comment]
I've pushed a possible fix for this, if you could follow the [manual installation instructions](https://github.com/dragonwocky/obsidian-tray#manual) to test it out before I release it to the Obsidian marketplace that'd be really helpful. Thanks!

**Comment by youngboy** [comment]
after clicked the `Close Vault`, the obsidian still shows in activity.

<img width="349" alt="image" src="https://github.com/dragonwocky/obsidian-tray/assets/2573063/c013d44a-1921-4cab-9396-8d739484a60c">

**Comment by youngboy** [comment]
<img width="607" alt="image" src="https://github.com/dragonwocky/obsidian-tray/assets/2573063/f28e2c7b-7945-4b14-83af-5b4e13d7e79e">

Can't debug or see any logs after `win.destroy()`, maybe can't reach the quitting code after destroy ?

**Comment by dragonwocky** [comment]
Hmm. Can you try adding in a `BrowserWindow.getAllWindows().forEach(win => win.show)` to see what you get? It's possible that there is a window still hiding somewhere in the background that doesn't get closed properly.

**Comment by dragonwocky** [comment]
Interesting. Would you mind showing me a screen recording of that, if possible? I can't replicate it myself, so I'm guessing it's another macOS-specific issue...

**Comment by youngboy** [comment]
https://github.com/dragonwocky/obsidian-tray/assets/2573063/f12392fd-37bd-4bb3-8219-c45c0f32b9a9

**Comment by dragonwocky** [comment]
That is rather odd.

**Comment by youngboy** [comment]
IMHO, It seems that if both vaults use the tray and their settings are different, it won't be straightforward to revert to the default behavior when exiting the first vault. The best approach might be to store the settings persistently within the app's internal data, don't know if obsidian support this.

**Comment by youngboy** [comment]
thank you so much for details explaination.

> The only think I can think of is that possibly app.dock.hide() is getting called somewhere/somehow when close vault is pressed?

I just tested it, can confirm that is not the case, hide is not being called when press closeVault.

add `showTaskbarIcons` in  closeVault will bring dock/menu back, but don't know how it works for vault-specific. maybe after `win.destroy` no more code logic will get executed ,

```
diff --git a/main.js b/main.js
index 305bf89..d464ebf 100644
--- a/main.js
+++ b/main.js
@@ -124,13 +127,17 @@ const setLaunchOnStartup = () => {
     app.exit(0);
   },
   closeVault = () => {
     log(LOG_CLEANUP);
     unregisterHotkeys();
     allowWindowClose();
+    showTaskbarIcons()
     destroyTray();
-    for (const win of getWindows()) win.destroy();
-    // force app quit if no windows remain on macos
-    if (!BrowserWindow.getAllWindows().length) app.quit();
+    const obsidianWindows = BrowserWindow.getAllWindows();
+    if (obsidianWindows.length === getWindows().length) {
+      app.quit()
+    } else {
+      getWindows().forEach(win => win.destroy())
+    };
   };

 const addQuickNote = () => {
```

**Comment by dragonwocky** [comment]
> Adding showTaskbarIcons within closeVault does bring the dock and menu back

I see. Just to confirm, the secondary vault definitely didn't have the tray running in it, did it? Could the windows of the secondary vault be pulled up from the dock/menubar before the first vault was closed? (Or could only the first vault be pulled up from the dock/menubar before it was closed?)

> It seems that once win.destroy() is called, no further code logic gets executed.

Yep - `win.destroy()` includes destroying the current window, which cuts off code execution.

**Comment by youngboy** [comment]
> Just to confirm, the secondary vault definitely didn't have the tray running in it, did it?

the secondary value didn't have tray running, it is new created vault and without any plugins installed. 

> Could the windows of the secondary vault be pulled up from the dock/menubar before the first vault was closed

not, it can't. dock/menubar is invisible at the time when first vault that enable hide taskbar icon settings.

**Comment by dragonwocky** [comment]
> not, it can't. dock/menubar is invisible at the time when first vault that enable hide taskbar icon settings.

Gotcha. But if `hide taskbar icon` is disabled, then does everything work fine? Just making sure I understand exactly what's going on.

**Comment by youngboy** [comment]
> > not, it can't. dock/menubar is invisible at the time when first vault that enable hide taskbar icon settings.
> 
> Gotcha. But if `hide taskbar icon` is disabled, then does everything work fine? Just making sure I understand exactly what's going on.

yes, works fine when disable

**Comment by dragonwocky** [comment]
Thanks for all the debugging, I think I've settled on a reasonable solution. Now released.
